// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* country.h
   Generated by wsdl2h 2.8.106 from http://localhost:8080/ws/countries.wsdl and typemap.dat
   2020-09-15 17:14:36 GMT

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE.

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on country.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://www.baeldung.com/springsoap/gen                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $SIZE typemap variable:                                                    *
 *   int                                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to 'typemap.dat' then rerun wsdl2h (use wsdl2h -t typemap.dat):

ns1 = "http://www.baeldung.com/springsoap/gen"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://www.baeldung.com/springsoap/gen"
//gsoap ns1   schema namespace:	http://www.baeldung.com/springsoap/gen
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://www.baeldung.com/springsoap/gen                                   *
 *                                                                            *
\******************************************************************************/

/// @brief "http://www.baeldung.com/springsoap/gen":currency is a simpleType restriction of type xs:string.
///
/// @note The enum values are prefixed with "ns1__currency__" to prevent name clashes: use wsdl2h option -e to omit this prefix or use option -c++11 for scoped enumerations
enum ns1__currency
{
	ns1__currency__GBP,	///< xs:string value="GBP"
	ns1__currency__EUR,	///< xs:string value="EUR"
	ns1__currency__PLN,	///< xs:string value="PLN"
};


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://www.baeldung.com/springsoap/gen                                   *
 *                                                                            *
\******************************************************************************/

/// @brief "http://www.baeldung.com/springsoap/gen":country is a complexType.
///
/// @note struct ns1__country operations:
/// - ns1__country* soap_new_ns1__country(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default_ns1__country(struct soap*, ns1__country*) default initialize members
/// - int soap_read_ns1__country(struct soap*, ns1__country*) deserialize from a source
/// - int soap_write_ns1__country(struct soap*, ns1__country*) serialize to a sink
/// - ns1__country* soap_dup_ns1__country(struct soap*, ns1__country* dst, ns1__country *src) returns deep copy of ns1__country src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del_ns1__country(ns1__country*) deep deletes ns1__country data members, use only on dst after soap_dup_ns1__country(NULL, ns1__country *dst, ns1__country *src) (use soapcpp2 -Ed)
struct ns1__country
{
/// Element "name" of type xs:string.
    char*                                name                           1;	///< Required element.
/// Element "population" of type xs:int.
    int                                  population                     1;	///< Required element.
/// Element "capital" of type xs:string.
    char*                                capital                        1;	///< Required element.
/// Element "currency" of type "":currency.
    enum ns1__currency                   currency                       1;	///< Required element.
};

/// @brief Top-level root element "http://www.baeldung.com/springsoap/gen":getCountryRequest
/// @brief "http://www.baeldung.com/springsoap/gen":getCountryRequest is a complexType.
///
/// @note struct _ns1__getCountryRequest operations:
/// - _ns1__getCountryRequest* soap_new__ns1__getCountryRequest(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns1__getCountryRequest(struct soap*, _ns1__getCountryRequest*) default initialize members
/// - int soap_read__ns1__getCountryRequest(struct soap*, _ns1__getCountryRequest*) deserialize from a source
/// - int soap_write__ns1__getCountryRequest(struct soap*, _ns1__getCountryRequest*) serialize to a sink
/// - _ns1__getCountryRequest* soap_dup__ns1__getCountryRequest(struct soap*, _ns1__getCountryRequest* dst, _ns1__getCountryRequest *src) returns deep copy of _ns1__getCountryRequest src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns1__getCountryRequest(_ns1__getCountryRequest*) deep deletes _ns1__getCountryRequest data members, use only on dst after soap_dup__ns1__getCountryRequest(NULL, _ns1__getCountryRequest *dst, _ns1__getCountryRequest *src) (use soapcpp2 -Ed)
struct _ns1__getCountryRequest
{
/// Element "name" of type xs:string.
    char*                                name                           1;	///< Required element.
};

/// @brief Top-level root element "http://www.baeldung.com/springsoap/gen":getCountryResponse
/// @brief "http://www.baeldung.com/springsoap/gen":getCountryResponse is a complexType.
///
/// @note struct _ns1__getCountryResponse operations:
/// - _ns1__getCountryResponse* soap_new__ns1__getCountryResponse(struct soap*, int num) allocate and default initialize one or more values (an array)
/// - soap_default__ns1__getCountryResponse(struct soap*, _ns1__getCountryResponse*) default initialize members
/// - int soap_read__ns1__getCountryResponse(struct soap*, _ns1__getCountryResponse*) deserialize from a source
/// - int soap_write__ns1__getCountryResponse(struct soap*, _ns1__getCountryResponse*) serialize to a sink
/// - _ns1__getCountryResponse* soap_dup__ns1__getCountryResponse(struct soap*, _ns1__getCountryResponse* dst, _ns1__getCountryResponse *src) returns deep copy of _ns1__getCountryResponse src into dst, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - soap_del__ns1__getCountryResponse(_ns1__getCountryResponse*) deep deletes _ns1__getCountryResponse data members, use only on dst after soap_dup__ns1__getCountryResponse(NULL, _ns1__getCountryResponse *dst, _ns1__getCountryResponse *src) (use soapcpp2 -Ed)
struct _ns1__getCountryResponse
{
/// Element "country" of type "":country.
    struct ns1__country*                 country                        1;	///< Required element.
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://www.baeldung.com/springsoap/gen                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://www.baeldung.com/springsoap/gen                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	CountriesPortSoap11 
//gsoap ns1  service type:	CountriesPort 
//gsoap ns1  service port:	http://localhost:8080/ws 
//gsoap ns1  service namespace:	http://www.baeldung.com/springsoap/gen 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Service Bindings

  - @ref CountriesPortSoap11

@section Service_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page CountriesPortSoap11 Binding "CountriesPortSoap11"

@section CountriesPortSoap11_operations Operations of Binding "CountriesPortSoap11"

  - @ref __ns1__getCountry

@section CountriesPortSoap11_ports Default endpoints of Binding "CountriesPortSoap11"

  - http://localhost:8080/ws

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   CountriesPortSoap11                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getCountry                                                        *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getCountry" of service binding "CountriesPortSoap11".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost:8080/ws

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getCountry(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    struct _ns1__getCountryRequest*     ns1__getCountryRequest,
    // output parameters:
    struct _ns1__getCountryResponse    *ns1__getCountryResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getCountry(
    struct soap *soap,
    // input parameters:
    struct _ns1__getCountryRequest*     ns1__getCountryRequest,
    // output parameters:
    struct _ns1__getCountryResponse    *ns1__getCountryResponse
  );
@endcode

*/

//gsoap ns1  service method-protocol:	getCountry SOAP
//gsoap ns1  service method-style:	getCountry document
//gsoap ns1  service method-encoding:	getCountry literal
//gsoap ns1  service method-action:	getCountry ""
//gsoap ns1  service method-output-action:	getCountry Response
int __ns1__getCountry(
    struct _ns1__getCountryRequest*     ns1__getCountryRequest,	///< Input parameter
    struct _ns1__getCountryResponse    *ns1__getCountryResponse	///< Output parameter
);

/** @page CountriesPortSoap11 Binding "CountriesPortSoap11"

@section CountriesPortSoap11_policy_enablers Policy Enablers of Binding "CountriesPortSoap11"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/** @page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings that are contractually bound by WSDLs and
are auto-generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data
bindings are adopted from XML schemas as part of the WSDL types section or when
running wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

@note The following readers and writers are C/C++ data type (de)serializers
auto-generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

@note Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

@note Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

@note The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_set_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_set_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


*/

/**

@section ns1 Top-level root elements of schema "http://www.baeldung.com/springsoap/gen"

  - <ns1:getCountryRequest> @ref _ns1__getCountryRequest
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getCountryRequest(struct soap*, struct _ns1__getCountryRequest*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getCountryRequest(struct soap*, struct _ns1__getCountryRequest*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getCountryRequest(struct soap*, const char *URL, struct _ns1__getCountryRequest*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getCountryRequest(struct soap*, const char *URL, struct _ns1__getCountryRequest*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getCountryRequest(struct soap*, const char *URL, struct _ns1__getCountryRequest*);
    soap_POST_recv__ns1__getCountryRequest(struct soap*, struct _ns1__getCountryRequest*);
    @endcode

  - <ns1:getCountryResponse> @ref _ns1__getCountryResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getCountryResponse(struct soap*, struct _ns1__getCountryResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getCountryResponse(struct soap*, struct _ns1__getCountryResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__getCountryResponse(struct soap*, const char *URL, struct _ns1__getCountryResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__getCountryResponse(struct soap*, const char *URL, struct _ns1__getCountryResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__getCountryResponse(struct soap*, const char *URL, struct _ns1__getCountryResponse*);
    soap_POST_recv__ns1__getCountryResponse(struct soap*, struct _ns1__getCountryResponse*);
    @endcode

*/

/* End of country.h */
